[project]
name = "image-extracter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "selenium>=4.32.0",
    "webdriver-manager>=4.0.2",
]
